version: 2
jobs: 
        build:
                working_directory:  ~/starter
                environment: 
                        - CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
                docker:
                        - image: circleci/node:4.8.3
                steps:
                        - checkout
                        - setup_remote_docker
                        - run:
                                name: Install Google Cloud
                                command: curl https://sdk.cloud.google.com | bash
                        - run: 
                                command: ~/google-cloud-sdk/bin/gcloud version
                        - run:
                                command: echo ${GOOGLE_AUTH} | base64 -i --decode > ${HOME}/gcp-key.json
                        - run:
                                command: ~/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
                        - run: 
                                command: ~/google-cloud-sdk/bin/gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
                        - run: 
                                command: ~/google-cloud-sdk/bin/gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
                        - run: 
                                command: ~/google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
                        - run: 
                                command: docker build -t gcr.io/${GOOGLE_PROJECT_ID}/circleci-node:$CIRCLE_SHA1 .
                        - run:
                                command: docker tag gcr.io/${GOOGLE_PROJECT_ID}/circleci-node:$CIRCLE_SHA1 gcr.io/${GOOGLE_PROJECT_ID}/circleci-node:latest
                        - run: 
                                command: ~/google-cloud-sdk/bin/gcloud docker -- push gcr.io/${GOOGLE_PROJECT_ID}/circleci-node:$CIRCLE_SHA1
                        - run:
                                command: ~/google-cloud-sdk/bin/gcloud components install kubectl
                        - run:
                                command: ~/google-cloud-sdk/bin/kubectl run circleci-node --image=gcr.io/${GOOGLE_PROJECT_ID}/circleci-node:$CIRCLE_SHA1 --port 8080
